version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  deploy-docker-ecr:
    parameters:
      deploy-env:
        description: Deployment tier/stage
        type: string
    executor: aws-cli/default
    environment:
      AWS_ECR_URL: ${AWS_ECR_ACCOUNT_URL}/playxiangqi/archive
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - aws-ecr/ecr-login
      - run:
          name: Build Docker Image
          command: |
            make docker-<< parameters.deploy-env >>
      - run:
          name: Deploy Docker Image
          command: make push-<< parameters.deploy-env >>
  deploy-ecs-update:
    parameters:
      deploy-env:
        description: Deployment tier/stage
        type: string
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - aws-ecs/update-service:
          family: << parameters.deploy-env >>-archive-task
          cluster-name: << parameters.deploy-env >>-archive-cluster
          service-name: << parameters.deploy-env >>-archive-service
          force-new-deployment: true

workflows:
  deploy-dev:
    jobs:
      - deploy-docker-ecr:
          name: dev-deploy-docker-ecr
          context: AWS
          deploy-env: dev
          filters:
            branches:
              only: master
      - deploy-ecs-update:
          name: dev-deploy-ecs-update
          context: AWS
          deploy-env: dev
          requires:
            - dev-deploy-docker-ecr
          filters:
            branches:
              only: master
